spring.application.name=barber-api

spring.datasource.url=jdbc:postgresql://ep-wandering-wave-a4h0p4af-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CwZpHsy37ofL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect